### ISSUE TITLE
Error creating USER :) plus typo

### ISSUE THREAD

**Issue by palladius** [DeviaVir/terraform-provider-gsuite#123]
1. I'm using your examples and a quick typo:

```
 name {
    family_name = "Sillevis"
    given_name  = "Chase"
  }
```
should be (note the equal sign):
```
 name = {
    family_name = "Sillevis"
    given_name  = "Chase"

  }
```

2. now back to the error:

* attaching [crash.log](https://github.com/DeviaVir/terraform-provider-gsuite/files/4096814/crash.log)
* attaching simple code
```
resource "gsuite_user" "developer" {
  aliases = [
    "tf-dev@oliardia.mygbiz.com"
  ]
  name = {
    # definition: https://github.com/DeviaVir/terraform-provider-gsuite/blob/master/gsuite/resource_user.go
    family_name = "TF McDeveloper"
    given_name  = "TF Riccardo"
  }
  external_ids {
    type  = "organization"
    value = "615578690183"
  }
  update_existing = true
}
```

**Comment by DeviaVir** [comment]
stack trace from crash.log:
```
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: panic: runtime error: invalid memory address or nil pointer dereference
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xe45e1c]
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36:
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: goroutine 28 [running]:
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: github.com/DeviaVir/terraform-provider-gsuite/gsuite.resourceUserCreate(0xc00010ca80, 0xf75f00, 0xc00017e0e0, 0x
2, 0x1ab8f60)
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36:  /go/src/github.com/DeviaVir/terraform-provider-gsuite/gsuite/resource_user.go:451 +0x1aec
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00010bb00, 0xc0000bee10, 0xc00000d6
c0, 0xf75f00, 0xc00017e0e0, 0xc000073d01, 0xc000215e30, 0xc000073d78)
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36:  /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/s
chema/resource.go:305 +0x365
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00010bd00, 0xc0003bb918, 0xc0000bee
10, 0xc00000d6c0, 0xc000073ef8, 0xc00000e568, 0xf6f660)
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36:  /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/s
chema/provider.go:294 +0x99
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00
000ea58, 0x1341fa0, 0xc0004342d0, 0xc00004c660, 0xc00000ea58, 0xc0004342d0, 0xc0000b1a80)
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36:  /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/github.com/hashicorp/terraform-plugin-sdk/internal
/helper/plugin/grpc_provider.go:885 +0x882
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10bbe60, 0x
c00000ea58, 0x1341fa0, 0xc0004342d0, 0xc00004c420, 0x0, 0x1341fa0, 0xc0004342d0, 0xc000018000, 0x52a)
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36:  /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/github.com/hashicorp/terraform-plugin-sdk/internal
/tfplugin5/tfplugin5.pb.go:3189 +0x217
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000da000, 0x134fd80, 0xc0004e8900, 0xc00027c000, 0xc000414e
10, 0x1a8d040, 0x0, 0x0, 0x0)
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36:  /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/google.golang.org/grpc/server.go:995 +0x460
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: google.golang.org/grpc.(*Server).handleStream(0xc0000da000, 0x134fd80, 0xc0004e8900, 0xc00027c000, 0x0)
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36:  /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/google.golang.org/grpc/server.go:1275 +0xd97
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004ea170, 0xc0000da000, 0x134fd80, 0xc0004e8900, 0xc00027c000)
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36:  /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/google.golang.org/grpc/server.go:710 +0xbb
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-01-22T12:17:10.293+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36:  /go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020-01-22T12:17:10.296+0100 [DEBUG] plugin: plugin process exited: path=/usr/local/google/home/ricc/.terraform.d/plugins/terraform-provider-gsuite_v0.1.36 pid=73745 error="exit status 2"
```

**Comment by DeviaVir** [comment]
I have a PR up with a fix, if you set `update_existing = false` this should not happen (it did not find an existing user to update)

**Comment by palladius** [comment]
Thanks for the SUPER FAST update! I love your repo! 
Actually it crashes also with update_existing = false :/ 

[...]
gsuite_user.developer: Creating...

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xe45e1c]
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: 
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: goroutine 41 [running]:
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: github.com/DeviaVir/terraform-provider-gsuite/gsuite.resourceUserCreate(0xc00017cbd0, 0xf75f00, 0xc00010c1c0, 0x2, 0x1ab8f60)
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: 	/go/src/github.com/DeviaVir/terraform-provider-gsuite/gsuite/resource_user.go:451 +0x1aec
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00010bb00, 0xc000412050, 0xc0005ca5a0, 0xf75f00, 0xc00010c1c0, 0xc000572901, 0xc0003fd4a0, 0xc000572a18)
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: 	/go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:305 +0x365
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00010bd00, 0xc0003a9918, 0xc000412050, 0xc0005ca5a0, 0xc000572a08, 0xc000444928, 0xf6f660)
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: 	/go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ea60, 0x1341fa0, 0xc0003ddbf0, 0xc000258ea0, 0xc00000ea60, 0xc0003ddbf0, 0xc000177a80)
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: 	/go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x882
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10bbe60, 0xc00000ea60, 0x1341fa0, 0xc0003ddbf0, 0xc000258e40, 0x0, 0x1341fa0, 0xc0003ddbf0, 0xc00022cf00, 0x4e5)
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: 	/go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000da000, 0x134fd80, 0xc000574f00, 0xc0003ae400, 0xc0005ae3c0, 0x1a8d040, 0x0, 0x0, 0x0)
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: 	/go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/google.golang.org/grpc/server.go:995 +0x460
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: google.golang.org/grpc.(*Server).handleStream(0xc0000da000, 0x134fd80, 0xc000574f00, 0xc0003ae400, 0x0)
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: 	/go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/google.golang.org/grpc/server.go:1275 +0xd97
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004481f0, 0xc0000da000, 0x134fd80, 0xc000574f00, 0xc0003ae400)
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: 	/go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/google.golang.org/grpc/server.go:710 +0xbb
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-01-22T12:58:02.074+0100 [DEBUG] plugin.terraform-provider-gsuite_v0.1.36: 	/go/src/github.com/DeviaVir/terraform-provider-gsuite/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020-01-22T12:58:02.076+0100 [DEBUG] plugin: plugin process exited: path=/usr/local/google/home/ricc/.terraform.d/plugins/terraform-provider-gsuite_v0.1.36 pid=116827 error="exit status 2"
2020/01/22 12:58:02 [DEBUG] gsuite_user.developer: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/01/22 12:58:02 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/01/22 12:58:02 [TRACE] EvalMaybeTainted: gsuite_user.developer encountered an error during creation, so it is now marked as tainted
2020/01/22 12:58:02 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/01/22 12:58:02 [TRACE] EvalWriteState: removing state object for gsuite_user.developer
2020/01/22 12:58:02 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/01/22 12:58:02 [TRACE] EvalApplyProvisioners: gsuite_user.developer has no state, so skipping provisioners
2020/01/22 12:58:02 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/01/22 12:58:02 [TRACE] EvalMaybeTainted: gsuite_user.developer encountered an error during creation, so it is now marked as tainted
2020/01/22 12:58:02 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/01/22 12:58:02 [TRACE] EvalWriteState: removing state object for gsuite_user.developer
2020/01/22 12:58:02 [TRACE] <root>: eval: *terraform.EvalIf
2020/01/22 12:58:02 [TRACE] <root>: eval: *terraform.EvalIf
2020/01/22 12:58:02 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/01/22 12:58:02 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/01/22 12:58:02 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/01/22 12:58:02 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/01/22 12:58:02 [TRACE] [walkApply] Exiting eval tree: gsuite_user.developer
2020/01/22 12:58:02 [TRACE] vertex "gsuite_user.developer": visit complete
2020/01/22 12:58:02 [TRACE] dag/walk: upstream of "provider.gsuite (close)" errored, so skipping
2020/01/22 12:58:02 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/01/22 12:58:02 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/01/22 12:58:02 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2020/01/22 12:58:02 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2020/01/22 12:58:02 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020/01/22 12:58:02 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/01/22 12:58:02 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-01-22T12:58:02.083+0100 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by DeviaVir** [comment]
Building 0.1.37

**Comment by DeviaVir** [comment]
https://github.com/DeviaVir/terraform-provider-gsuite/releases/tag/v0.1.38

Can you try with that release and let me know if you still run into issues?

**Comment by DeviaVir** [comment]
oops, please try with https://github.com/DeviaVir/terraform-provider-gsuite/releases/tag/v0.1.39 instead

**Comment by palladius** [comment]
trying now.
PS My colleague Michele Chiappalone says hi :)

**Comment by palladius** [comment]
Bingo! It stops crashing:


Error: [ERROR] Error creating user: Post https://www.googleapis.com/admin/directory/v1/users?alt=json&prettyPrint=false: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error": "unauthorized_client",
  "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."
}

Still fails, but fails differently :)

**Comment by DeviaVir** [comment]
Ah, make sure to check which scopes you are giving it (both in admin.google.com and in the TF provider)

**Comment by palladius** [comment]
Great point, Michele told me the same.
On provider I gave ZERO scopes (meaning, probably using your defaults).
The user provisioned only had Admin.User and Admin.Group. Once I added the schema scope, all worked like a CHARM.

DeviaVir, you *ROCK* and if you are a Googler please ping me (ricc@) offline.
